from enum import Enum

class Action(Enum):
    MENU_BACK = "MENU_BACK"
    MENU_CONFIRM = "MENU_CONFIRM"

    PLAYER_SHOOT = "PLAYER_SHOOT"

    PLAYER_MOVEMENT_FORWARD = "PLAYER_MOVEMENT_FORWARD"
    PLAYER_MOVEMENT_BACKWARD = "PLAYER_MOVEMENT_BACKWARD"
    PLAYER_MOVEMENT_RIGHT = "PLAYER_MOVEMENT_RIGHT"
    PLAYER_MOVEMENT_LEFT = "PLAYER_MOVEMENT_LEFT"
    PLAYER_MOVEMENT_FORWARD_ALT = "PLAYER_MOVEMENT_FORWARD_ALT"
    PLAYER_MOVEMENT_BACKWARD_ALT = "PLAYER_MOVEMENT_BACKWARD_ALT"
    PLAYER_MOVEMENT_RIGHT_ALT = "PLAYER_MOVEMENT_RIGHT_ALT"
    PLAYER_MOVEMENT_LEFT_ALT = "PLAYER_MOVEMENT_LEFT_ALT"

    PLAYER_WEAPON_ONE = "PLAYER_WEAPON_ONE"
    PLAYER_WEAPON_TWO = "PLAYER_WEAPON_TWO"
    PLAYER_WEAPON_THREE = "PLAYER_WEAPON_THREE"
    PLAYER_WEAPON_ONE_ALT = "PLAYER_WEAPON_ONE_ALT"
    PLAYER_WEAPON_TWO_ALT = "PLAYER_WEAPON_TWO_ALT"
    PLAYER_WEAPON_THREE_ALT = "PLAYER_WEAPON_THREE_ALT"